# Generate raw file links for each repository
for REPO in $REPO_LIST; do
  echo "Processing repository: $REPO"

  # Clone the target repository
  git clone "https://github.com/${{ github.repository_owner }}/$REPO.git"

  # Create a raw links file
  LINK_FILE="${REPO}-links.txt"

  # Find all files in the repository and generate raw links
  find $REPO -type f | while read FILE; do
    # Generate raw link, adjusting the file path to remove the repository name
    RELATIVE_PATH="${FILE#*/$REPO/}"  # Remove the repository name from the file path
    RAW_LINK="https://raw.githubusercontent.com/${{ github.repository_owner }}/$REPO/main/$RELATIVE_PATH"
    echo $RAW_LINK >> $LINK_FILE
  done

  # Commit and push the generated link file
  git add $LINK_FILE
  git commit -m "Generate file links list for $REPO"
  git push

  # Clean up by deleting the cloned repository
  rm -rf $REPO
done
